### ISSUE TITLE
Cannot find ops.modules

### ISSUE THREAD

**Issue by frogbam** [zehuichen123/AutoAlignV2#1]
Thank you for sharing your wonderful work!

It seems that deform attention module is implemented in MSDeformAttn in ops.modules.
However, I can't find ops.modules folder anywhere.

Could you please upload ops.modules ?

Thanks.

**Comment by zehuichen123** [comment]
Thanks for reporting the bug. We use the same one in the DeformDETR repo (https://github.com/fundamentalvision/Deformable-DETR). We will replace this ops with the one provided in the mmcv to avoid this problem later.

**Comment by frogbam** [comment]
@zehuichen123 Thanks a lot.
