### ISSUE TITLE
why keep only one crop when use depth gt-aug?

### ISSUE THREAD

**Issue by AndyYuan96** [zehuichen123/AutoAlignV2#12]
Hi, I wonder why you only keep one image gtaug crop in nuscenes dataset, rather than 6 image crop corresponding to 6 image.

**Comment by ZecCheng** [comment]
I have the same question.

**Comment by lihuashengmax** [comment]
好好想想，在绝大多数情况下，gt框也只能落在一张图片的视角下吧
