### ISSUE TITLE
yolox training config

### ISSUE THREAD

**Issue by AndyYuan96** [zehuichen123/AutoAlignV2#19]
Hi, I just wonder can I get your yolox training config on NuScenes dataset, as I the yolox's mAP I trained is low than the performance you provide, many thanks.

**Comment by zehuichen123** [comment]
Hi, since I've left the company, it's hard for me to find the training config. btw, do you use the YOLOX COCO pretrain and enlarge the training image size to 800? I remembered that the image size is critical to the final detection performance.

**Comment by AndyYuan96** [comment]
> Hi, since I've left the company, it's hard for me to find the training config. btw, do you use the YOLOX COCO pretrain and enlarge the training image size to 800? I remembered that the image size is critical to the final detection performance.

I figure out why, sorry for bother you, I change random_size_range parameter according the other project, thanks.

**Comment by AndyYuan96** [comment]
can I ask except for image size and coco pretrain weight, what do you change about yolox config from mmdet, I use mmdet2.25 to train yolox-tiny on nuimage, though the mAP performance is right, the feature map visualization have a large difference with the weight you provide, change in training config maybe like num_last_epochs, and how do you specify the img_norm_config, as yolox don't use normlization.
thanks for reply.

**Comment by AndyYuan96** [comment]
can I ask except for image size and coco pretrain weight, what do you change about yolox config from mmdet, I use mmdet2.25 to train yolox-tiny on nuimage, though the mAP performance is right, the feature map visualization have a large difference with the weight you provide, change in training config maybe like num_last_epochs, and how do you specify the img_norm_config, as yolox don't use normlization.
thanks for reply.

**Comment by zehuichen123** [comment]
Sorry, but I have no memory of this since the code was written about one year ago. :(
