### ISSUE TITLE
Reproduction Problem

### ISSUE THREAD

**Issue by yinjunbo** [zehuichen123/AutoAlignV2#6]
Thanks for your nice work. 
But I get the following results with your pretrained model `centerpoint_voxel_nus_8subset_bs4_img1_nuimg_detach_deform_multipts`.
```
smAP: 0.5653                                                                                                                                                                  
mATE: 0.3300
mASE: 0.2699
mAOE: 0.4220
mAVE: 0.4690
mAAE: 0.1972
NDS: 0.6138
```
By re-training from scratch, I get
```
mAP: 0.5622                                                                                                                                                                    
mATE: 0.3244
mASE: 0.2704
mAOE: 0.4520
mAVE: 0.4817
mAAE: 0.1992
NDS: 0.6084
```
This is lower than that in the readme (58.5 mAP and 63.2 NDS). Is there something I missed?

**Comment by buaazeus** [comment]
I tried to train the model from sratch and get the issue below.

File "./AutoAlignV2/mmdet3d/core/bbox/structures/base_box3d.py", line 6, in <module>
    from mmdet3d.ops.iou3d import iou3d_cuda
ModuleNotFoundError: No module named 'mmdet3d.ops'

I didn`t find mmdet3d.ops in the code, I tried to install mmdet3d seperately, but still not working. Any advice?
Thank you.

**Comment by zehuichen123** [comment]
@yinjunbo Hi, do you enable the TTA when testing? This performance is tested with TTA(double flip during inference).

**Comment by yinjunbo** [comment]
> @yinjunbo Hi, do you enable the TTA when testing? This performance is tested with TTA(double flip during inference).

I didn‘t enable the TTA. Btw, do you mean all the model results in the main paper and readme are evaluated with TTA, since I didn't find related sentence in the paper.

**Comment by zehuichen123** [comment]
Sadly yes. I forgot to disenable them in all my experiments...

**Comment by yinjunbo** [comment]
> Sadly yes. I forgot to disenable them in all my experiments...

Got it, thanks for you kind reply.

**Comment by yinjunbo** [comment]
Hi, @zehuichen123 , 
I recently finish the training of the LiDAR-only baseline model (`centerpoint_voxel_nus_8subset_dv_aug.py`), and get **61.7NDS and 54.2mAP** (w/o TTA, on 1/8 set). 
By contrast, the multimodl model (`centerpoint_voxel_nus_8subset_bs4_img1_nuimg_detach_deform_multipts.py`) get **61.6NDS and 56.3mAP**. 
Is this normal that the NDS is just not improved? Or what's the reason causes this results?
Looking forward to your reply!

**Comment by zehuichen123** [comment]
I think it is abnormal. The NDS should also be improved. How about the TTA results of this two models?

**Comment by yinjunbo** [comment]
> I think it is abnormal. The NDS should also be improved. How about the TTA results of this two models?

The TTA results of both models are as follows:
LiDAR-only: 56.44mAP, 63.79NDS;
Multimodal: 58.39mAP, 63.57NDS.

Could you give some advice to solve this problem?

**Comment by zehuichen123** [comment]
Currently I have no idea why this happens. Could you get the right score with the provided AutoAlignV2 checkpoint? I may recheck the code after the DDL of cvpr :(

**Comment by zehuichen123** [comment]
I rechecked my code and I think it normal now... My reported baseline of CenterPoint is the original version, while the config I provided here is dynamic voxelization, which means the improvements of NDS on 1/8 subset mainly comes from DV... But the main results in the paper indicate that the AutoAlignV2 provides about 3 NDS improvements on fullest since the 62.xx mAP version is the dynamic-version of the CenterPoint.

**Comment by yinjunbo** [comment]
Ok. CenterPoint with dynamic voxelization should be the propoer
baseline. Hope you can further improve this and share the advice. Thx.

loveSnowBest ***@***.***> 于2022年10月22日周六 22:54写道：

**Comment by zehuichen123** [comment]
Thanks for your suggestion! I will update this in the readme to make it clear.
