### ISSUE TITLE
mmdet3d.ops missing issue

### ISSUE THREAD

**Issue by buaazeus** [zehuichen123/AutoAlignV2#7]
I tried to train the model from sratch and get the issue below.

File "./AutoAlignV2/mmdet3d/core/bbox/structures/base_box3d.py", line 6, in
from mmdet3d.ops.iou3d import iou3d_cuda
ModuleNotFoundError: No module named 'mmdet3d.ops'

I didn`t find mmdet3d.ops in the code, I tried to install mmdet3d seperately, but still not working. Any advice?
Thank you.

**Comment by zehuichen123** [comment]
You may refer to the Issue #1.

**Comment by buaazeus** [comment]
Thanks for the reply.
I cloned the Deformable DETR code.
cd Deformable DETR/models/ops
sh ./make.sh
I modify the from mmdet3d.ops.iou3d import iou3d_cuda to from DeformableDETR.models.ops.iou3d import iou3d_cuda.
Still not found the iou3d module.
Could you please further clarify?

**Comment by zehuichen123** [comment]
Sorry, I read your issue by mistake. I think it is unrelated to the #1... Do you compile mmdet3d followed by the official mmdet3d guide? Since you need to compile mmdet3d ops before using them.

**Comment by buaazeus** [comment]
Yes, I complied mmdet3d, does it require a specific version of mmdet3d?

**Comment by buaazeus** [comment]
![image](https://user-images.githubusercontent.com/48085677/194806840-d77b6b56-a08c-4439-959f-a9da2b8dc8fb.png)


Requirements are these four txts or all txts in requirement folder below?
![image](https://user-images.githubusercontent.com/48085677/194806959-b7d6cc33-99a3-4682-8cf1-271bccc27d4a.png)

**Comment by zehuichen123** [comment]
Sorry, it's my fault. I will update the ops code asap.

**Comment by buaazeus** [comment]
Thank you for the update.
This issue is fixed.

But I am facing another issue now.
ImportError: cannot import name 'ball_query_ext' from 'mmdet3d.ops.ball_query' (AutoAlignV2/mmdet3d/ops/ball_query/__init__.py)
Seems like mmdet3d compile issue.
Should I compile mmdet3d in AutoAlignV2/mmdet3d/?

I have compile mmdet3d seperately but it does not fix this.

**Comment by zhyever** [comment]
I guess you need to compile mmdet3d in autoalignv2

**Comment by buaazeus** [comment]
![image](https://user-images.githubusercontent.com/48085677/196327969-731d2bef-d9cf-4842-86a0-e0f5801af927.png)
There is no setup.py file or any other file in AutoAlignV2/mmdet3d/, I don't know how to compile here.

**Comment by zehuichen123** [comment]
Probably you can try `pip install -v -e .` under this repo.

**Comment by buaazeus** [comment]
(base) root@c53050a8c9e2:/workspace/home/jump/zeus/AutoAlignV2/mmdet3d# pip install -v -e .
Using pip 21.0.1 from /opt/conda/lib/python3.7/site-packages/pip (python 3.7)
Non-user install because site-packages writeable
Created temporary directory: /tmp/pip-ephem-wheel-cache-k4htqm9n
Created temporary directory: /tmp/pip-req-tracker-bvh2sswb
Initialized build tracking at /tmp/pip-req-tracker-bvh2sswb
Created build tracker: /tmp/pip-req-tracker-bvh2sswb
Entered build tracker: /tmp/pip-req-tracker-bvh2sswb
Created temporary directory: /tmp/pip-install-um3pav0c
ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /workspace/home/jump/zeus/AutoAlignV2/mmdet3d
Exception information:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 189, in _main
    status = self.run(options, args)
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 178, in wrapper
    return func(self, options, args)
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 287, in run
    reqs = self.get_requirements(args, options, finder, session)
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 352, in get_requirements
    use_pep517=options.use_pep517,
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/req/constructors.py", line 212, in install_req_from_editable
    parts = parse_req_from_editable(editable_req)
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/req/constructors.py", line 183, in parse_req_from_editable
    name, url, extras_override = parse_editable(editable_req)
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/req/constructors.py", line 96, in parse_editable
    raise InstallationError(msg)
pip._internal.exceptions.InstallationError: File "setup.py" not found. Directory cannot be installed in editable mode: /workspace/home/jump/zeus/AutoAlignV2/mmdet3d
Removed build tracker: '/tmp/pip-req-tracker-bvh2sswb'


I runned pip install -v -e . but got "setup.py" not found issue...
