### ISSUE TITLE
yolox performance on nuscenes

### ISSUE THREAD

**Issue by AndyYuan96** [zehuichen123/AutoAlignV2#8]
Hi, can I ask how is the 2d mAP of Pretrained YOLOX-800 and Pretrained YOLOX-640 on nuImage dataset.

**Comment by zehuichen123** [comment]
Sorry, I can not find the 640 results, but here is the 800 results: 
2022-02-04 04:29:26,053 - mmdet - INFO - Epoch(val) [12][2056]	bbox_mAP: 0.4260, bbox_mAP_50: 0.6690, bbox_mAP_75: 0.4520, bbox_mAP_s: 0.2290, bbox_mAP_m: 0.4210, bbox_mAP_l: 0.5550, bbox_mAP_copypaste: 0.426 0.669 0.452 0.229 0.421 0.555

**Comment by AndyYuan96** [comment]
> Sorry, I can not find the 640 results, but here is the 800 results:
> 2022-02-04 04:29:26,053 - mmdet - INFO - Epoch(val) [12][2056] bbox_mAP: 0.4260, bbox_mAP_50: 0.6690, bbox_mAP_75: 0.4520, bbox_mAP_s: 0.2290, bbox_mAP_m: 0.4210, bbox_mAP_l: 0.5550, bbox_mAP_copypaste: 0.426 0.669 0.452 0.229 0.421 0.555

thanks。

**Comment by zhanggang001** [comment]
> 

One more question, how to pretrain the YOLOX models on nuImage? following the training settings used for training YOLOX on COCO or following the setting in mmdetection3d? Thanks in advance.
